### Obtiene todos los turnos

GET http://127.0.0.1:3000/api/turneroweb/ HTTP/1.1

### Obtiene un turno específico

GET http://127.0.0.1:3000/api/turneroweb/6666553f2aa277402bcc028a HTTP/1.1

### Creo un turno

POST http://127.0.0.1:3000/api/turneroweb HTTP/1.1
Content-Type: application/json

{
    "fecha": "2024-06-08",
    "hora": "17:47",
    "categoria": "AAA",
    "numero": 0,
    "nombre": "valeria1",
    "estado": "en espera"
}

### Modifico un turno específico

PUT http://127.0.0.1:3000/api/turneroweb/6666553f2aa277402bcc028a HTTP/1.1
Content-Type: application/json

{
    "fecha": "2024-06-09",
    "hora": "17:47",
    "categoria": "perros",
    "numero": 1,
    "nombre": "virginia",
    "estado": "en espera"
}

### Modifico campo=valor de un turno específico

PATCH http://127.0.0.1:3000/api/turneroweb/cambiarcampo/6666553f2aa277402bcc028a/nombre/estela HTTP/1.1

### Elimino un turno específico

DELETE http://127.0.0.1:3000/api/turneroweb/6670a5fc1f25245dfd76f76c HTTP/1.1

### Elimino todos los turnos del día actual

DELETE http://127.0.0.1:3000/api/turneroweb/resetdia HTTP/1.1

### Obtengo todos los turnos por una categoría específica (Perros, Gatos, Exoticos, Vacunacion, Compras)

GET http://127.0.0.1:3000/api/turneroweb/proximos/Perros HTTP/1.1

### Cambio el estado de un turno según categoría y número

PUT http://127.0.0.1:3000/api/turneroweb/enespera/perros/1 HTTP/1.1

### Cambio el estado de un turno según categoría y número

PUT http://127.0.0.1:3000/api/turneroweb/atendiendo/perros/1 HTTP/1.1

### Cambio el estado de un turno según categoría y número

PUT http://127.0.0.1:3000/api/turneroweb/atendido/perros/1 HTTP/1.1

### Cambio el estado de un turno según categoría y número

PUT http://127.0.0.1:3000/api/turneroweb/cancelado/perros/1 HTTP/1.1
