GET http://127.0.0.1:3000/api/turneroweb/ HTTP/1.1

###

GET http://127.0.0.1:3000/api/turneroweb/6664d3323537ea864fc6ac08 HTTP/1.1

###

GET http://127.0.0.1:3000/api/turneroweb/6664d8502d8d9c2672607452 HTTP/1.1

###

POST http://127.0.0.1:3000/api/turneroweb HTTP/1.1
Content-Type: application/application/json

{
    "fecha": "2024-06-08",
    "hora": "17:47",
    "categoria": "Veterinaria para Perros",
    "numero": 0,
    "nombre": "juan",
    "estado": "en espera"
}


###

PUT http://127.0.0.1:3000/api/turneroweb/XXXXXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1
Content-Type: application/application/json

{
    "fecha": "2024-06-08",
    "hora": "17:47",
    "categoria": "Veterinaria para Perros",
    "numero": 0,
    "nombre": "juan",
    "estado": "en espera"
}

###

DELETE http://127.0.0.1:3000/api/turneroweb/XXXXXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1